name: Back-end tests

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install modules
      run: npm install
    - name: Run ESLint
      run: npm run lint
  post-login-tests:
    needs: eslint
    runs-on: ubuntu-latest
    container: cypress/browsers:node12.18.3-chrome87-ff82
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Run POST method tests on Login endpoint
        uses: cypress-io/github-action@v2
        with:
          command: npm run test:postLogin
  delete-products-tests:
    needs: eslint
    runs-on: ubuntu-latest
    container: cypress/browsers:node12.18.3-chrome87-ff82
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Run DELETE method tests on Products endpoint
        uses: cypress-io/github-action@v2
        with:
          command: npm run test:deleteProducts
  get-products-tests:
    needs: eslint
    runs-on: ubuntu-latest
    container: cypress/browsers:node12.18.3-chrome87-ff82
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Run GET method tests on Products endpoint
        uses: cypress-io/github-action@v2
        with:
          command: npm run test:getProducts
  post-products-tests:
    needs: eslint
    runs-on: ubuntu-latest
    container: cypress/browsers:node12.18.3-chrome87-ff82
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Run POST method tests on Products endpoint
        uses: cypress-io/github-action@v2
        with:
          command: npm run test:postProducts
  put-products-tests:
    needs: eslint
    runs-on: ubuntu-latest
    container: cypress/browsers:node12.18.3-chrome87-ff82
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Run PUT method tests on Products endpoint
        uses: cypress-io/github-action@v2
        with:
          command: npm run test:putProducts
  delete-users-tests:
    needs: eslint
    runs-on: ubuntu-latest
    container: cypress/browsers:node12.18.3-chrome87-ff82
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Run DELETE method tests on Users endpoint
        uses: cypress-io/github-action@v2
        with:
          command: npm run test:deleteUsers
  get-users-tests:
    needs: eslint
    runs-on: ubuntu-latest
    container: cypress/browsers:node12.18.3-chrome87-ff82
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Run GET method tests on Users endpoint
        uses: cypress-io/github-action@v2
        with:
          command: npm run test:getUsers
  post-users-tests:
    needs: eslint
    runs-on: ubuntu-latest
    container: cypress/browsers:node12.18.3-chrome87-ff82
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Run POST method tests on Users endpoint
        uses: cypress-io/github-action@v2
        with:
          command: npm run test:postUsers
  put-users-tests:
    needs: eslint
    runs-on: ubuntu-latest
    container: cypress/browsers:node12.18.3-chrome87-ff82
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Run PUT method tests on Users endpoint
        uses: cypress-io/github-action@v2
        with:
          command: npm run test:putUsers
    