name: Back-end tests

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install modules
      run: npm install
    - name: Run ESLint
      run: npm run lint
  cypress-tests-desktop:
    needs: eslint
    runs-on: ubuntu-latest
    container: cypress/browsers:node12.18.3-chrome87-ff82
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Run back-end tests
        uses: cypress-io/github-action@v2
        with:
          command: npm test